name = "imp"
version = "0.1.0"
defaultTargets = ["check"]

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
rev = "v4.18.0"

[[lean_lib]]
name = "Imp"

[[lean_lib]]
name = "Artifacts"

[[lean_exe]]
name = "check"
root = "Check"
