pre-commit:
  parallel: true
  jobs:
    - name: "Imp codebase"
      run: |
        lake build
      root: "imp/"
      glob: "imp/*.lean"

    - name: "FCP: uv package - lint"
      run: |
        uv run ruff check src
      root: "fcp/"
      glbo: "fcp/src/*.py"

    - name: "FCP: uv package - format"
      run: |
        uv run ruff format --check src
      root: "fcp/"
      glob: "fcp/src/*.py"

    - name: "FCP: uv package - typecheck"
      run: |
        uv run pyright
      root: "fcp/"
      glob: "fcp/src/*.py"

    - name: "FCP: uv package - test"
      run: |
        uv run pytest
      root: "fcp/"
      glob: "fcp/src/*.py"

    - name: "Communications"
      run: |
        make -q
      root: "comms/"
      glob: "comms/{*.typ,*.org}"
