pre-commit:
  parallel: true
  jobs:
    - name: "Imp codebase"
      run: |
        lake build
      root: "imp/"
      glob: "imp/*.lean"

    - name: "FCP: uv package"
      run: |
        uv run ruff check src --fix
        uv run ruff format src
        uv run pyright
        uv run pytest
      root: "fcp/"
      glob: "fcp/src/*.py"

    - name: "Communications"
      run: |
        make
      root: "comms/"
      glob: "comms/{*.typ,*.org}"
